# Generated by Django 3.2.7 on 2021-09-17 10:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Departement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_depart', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Enseignant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_enseigant', models.CharField(max_length=20)),
                ('post_nom_enseignant', models.CharField(max_length=20)),
                ('num_tel', models.CharField(max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='Universite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_univ', models.CharField(max_length=50)),
                ('single', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Promotion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_prom', models.CharField(max_length=50)),
                ('departement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.departement')),
            ],
        ),
        migrations.CreateModel(
            name='Faculte',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_fac', models.CharField(max_length=50)),
                ('universite', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.universite')),
            ],
        ),
        migrations.CreateModel(
            name='Etudiant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('matricule', models.CharField(max_length=20)),
                ('nom_etudiant', models.CharField(max_length=20)),
                ('post_nom_etudiant', models.CharField(max_length=20)),
                ('prenom_etudiant', models.CharField(max_length=20)),
                ('promotion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.promotion')),
            ],
        ),
        migrations.AddField(
            model_name='departement',
            name='faculte',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.faculte'),
        ),
        migrations.CreateModel(
            name='Cours',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=20)),
                ('nom_course', models.CharField(max_length=50)),
                ('enseignant', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='api.enseignant')),
                ('promotion', models.ManyToManyField(to='api.Promotion')),
            ],
        ),
    ]
