# Generated by Django 3.2.7 on 2021-09-21 11:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20210921_1006'),
    ]

    operations = [
        migrations.RenameField(
            model_name='enseignant',
            old_name='nom_enseigant',
            new_name='nom_enseignant',
        ),
    ]
