# Generated by Django 3.2.7 on 2021-09-21 15:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_auto_20210921_1347'),
    ]

    operations = [
        migrations.AddField(
            model_name='cours',
            name='departement',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='api.departement'),
            preserve_default=False,
        ),
    ]
