# Generated by Django 3.2.7 on 2021-09-21 15:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_cours_departement'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cours',
            old_name='nom_course',
            new_name='nom_cours',
        ),
    ]
