# Generated by Django 3.2.7 on 2021-09-21 21:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_auto_20210921_1601'),
    ]

    operations = [
        migrations.AddField(
            model_name='promotion',
            name='universite',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='api.universite'),
            preserve_default=False,
        ),
    ]
