# Generated by Django 3.2.7 on 2021-10-15 01:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_promotion_universite'),
    ]

    operations = [
        migrations.AddField(
            model_name='cours',
            name='cote',
            field=models.FileField(blank=True, null=True, upload_to='cotes/'),
        ),
    ]
