# Generated by Django 3.2.8 on 2021-10-17 22:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_cours_cote'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cotes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=20)),
                ('cote', models.DecimalField(decimal_places=2, max_digits=5)),
                ('ponderation', models.DecimalField(decimal_places=2, max_digits=5)),
                ('date', models.DateTimeField()),
                ('code', models.IntegerField()),
                ('cours', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.cours')),
                ('etudiant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.etudiant')),
            ],
        ),
    ]
