# Generated by Django 3.2.8 on 2021-10-17 22:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_cotes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cotes',
            name='label',
            field=models.CharField(choices=[('TD', 'Travail Dirigé'), ('TP', 'Travail Pratique'), ('INT', 'Interrogation'), ('EX', 'Examen')], max_length=50),
        ),
    ]
