# Generated by Django 3.2.8 on 2021-10-18 01:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_alter_cotes_label'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cotes',
            name='date',
            field=models.DateField(verbose_name='A remettre le'),
        ),
        migrations.AlterField(
            model_name='cotes',
            name='label',
            field=models.CharField(choices=[('TP', 'Travail Pratique'), ('TD', 'Travail Dirigé'), ('INT', 'Interrogation'), ('EX', 'Examen')], max_length=50, verbose_name='Type de travail'),
        ),
        migrations.AlterField(
            model_name='cotes',
            name='ponderation',
            field=models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Pondération'),
        ),
    ]
