# Generated by Django 3.2.8 on 2021-10-19 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_auto_20211018_0315'),
    ]

    operations = [
        migrations.AddField(
            model_name='cotes',
            name='ponderation_blobal',
            field=models.DecimalField(decimal_places=2, default=20, max_digits=5, verbose_name='Pondération global'),
            preserve_default=False,
        ),
    ]
