# Generated by Django 3.2.8 on 2021-10-21 01:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0014_cotes_ponderation_blobal'),
    ]

    operations = [
        migrations.AddField(
            model_name='cours',
            name='is_cote_submited',
            field=models.BooleanField(default=False),
        ),
    ]
